### ISSUE TITLE
Cpp get problem not working

### ISSUE THREAD

**Issue by BlueAndRose** [cc189/lintcode-cli#1]
Hi CC189

Just try out your amazing tool. I found the following error when running: lc g 3 cpp

>>> Get... problem_number: 3, file_postfix: cpp
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/lib/node_modules/lintcode-cli/src/api.js:244:40)
    at Request.self.callback (/usr/lib/node_modules/lintcode-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/usr/lib/node_modules/lintcode-cli/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/lintcode-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)

Seems to me lintCode returns html file while we are expecting JASON. 

This issue only happened with option CPP. Could be a issue from lintCode as well. 

Can you comment on this?

BR
Yi

**Comment by BlueAndRose** [comment]
**Problem found & Fixed**, has to do with some encoding scheme with LintCode.
CHANGE FILE api.js LINE 147 to

    const lang_file_to_lang_abbr = {
        'py' : 'Py3',
        'java' : 'Java',
        'cpp' : 'C%2B%2B',
        'js' : 'JS',
        'go': 'Go'
    };

CPP file has its special char %2B, not "+" sign. 

Whoever have the issue, change your file accordingly

CC189, if you read this, please update BR

Yi

**Comment by yangliu28** [comment]
Thanks @BlueAndRose
I ran into this problem as well, and found your answer before opening a new issue.
